version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - frontend-network
networks:
  frontend-network:
    driver: bridge 